version: "3.4"

services:
  zookeeper:
    image: bitnami/zookeeper
    restart: always
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: bitnami/kafka
    ports:
      - "9092:9092"
    restart: always
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
    depends_on:
      - zookeeper
  mongodb:
    image: mongo
    container_name: mongo-container
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=cbnuser
    #   - MONGO_INITDB_ROOT_PASSWORD=cbnpass#
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081

  mysql:
    image: mysql:latest
    container_name: mysql-container
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=techbankRootPsw
    restart: always
    volumes:
      - mysql_data_container:/var/lib/mysql

  adminer:
    image: adminer:latest
    container_name: adminer
    ports:
      - 8080:8080
    environment:
      - ADMINER_DEFAULT_SERVER=mysql-container
    restart: always

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
  mongodb_data_container:
    driver: local
  mysql_data_container:
    driver: local
   
networks:
  default:
    external:
      name: techbankNet
